name: CI

on: push

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - name: Test Refs
        run: echo "$SOME_VAR"
        env:
          SOME_VAR: ${{ github.ref }}

      - name: Linter
        run: npm run lint

      - name: Test Coverage
        run: npm run coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: coverage/lcov-report

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci

      - name: Build
        run: npm run build
