name: CI

on: push

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache Node Modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm ci

      - name: Test Refs
        run: echo "$SOME_VAR"
        env:
          SOME_VAR: ${{ github.ref }}

      - name: Lint
        run: npm run lint

      - name: Test Coverage
        run: npm run coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: test-coverage
          path: coverage/lcov-report

      - name: Build
        if: github.ref != 'refs/heads/master'
        run: npm run build
