name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker Image
        run: >
          gcloud builds submit
          --quiet
          --tag gcr.io/$GCP_PROJECT/$GCP_SERVICE:$GITHUB_SHA
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SERVICE: ${{ secrets.GCP_SERVICE }}

      - name: Deploy to Cloud Run
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GH_PA_TOKEN}}
          script: |
            github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              required_contexts: [],
            });
