name: Terraform

on:
  pull_request:
    branches:
      - master
    paths:
      - 'terraform/*'
  deployment:
    branches:
      - master

jobs:
  start-deployment:
    name: Start deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment'
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createDeploymentStatus({
              headers: {
                accept: 'application/vnd.github.flash-preview+json',
              },
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment.id,
              state: 'in_progress',
            })
  validate:
    name: Validate Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Setup terraform variables
        run: echo "revision = \"$GITHUB_SHA\"" > terraform.auto.tfvars

      - run: terraform fmt
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color

      - name: Terraform Apply
        if: github.event_name == 'deployment'
        run: terraform apply -auto-approve

  update-deployment:
    name: Update deployment status
    runs-on: ubuntu-latest
    if: always() && github.event_name == 'deployment'
    needs: validate
    steps:
      - uses: actions/github-script@v2
        env:
          STATUS: ${{ needs.validate.result }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const state = process.env.STATUS === 'success'
              ? 'success'
              : 'failure';
            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment.id,
              state,
            })
